language: haskell

ghc:
 - 7.8
 - 7.10

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install happy-1.19.3
 - sudo apt-get install alex-3.1.3
 - export PATH=~/.cabal/bin:$PATH # for newer alex
 - cabal update
 - cabal install alex happy

install:
 - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
 # -v2 provides useful information for debugging
 - cabal configure --enable-tests --enable-benchmarks -v2

 # this builds all libraries and executables
 # (including tests/benchmarks)
 - cabal build

 - cabal test
 - cabal check

 # tests that a source-distribution can be generated
 - cabal sdist

 # check that the generated source-distribution can be built & installed
 # - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
 #   cd dist/;
 #   if [ -f "$SRC_TGZ" ]; then
 #      cabal install "$SRC_TGZ";
 #   else
 #      echo "expected '$SRC_TGZ' not found";
 #      exit 1;
 #   fi
